<a href="https://colab.research.google.com/github/ArunKoundinya/DeepLearning/blob/main/posts/gradient_tape_learning/index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.constant(100.0)
b = tf.constant(10.0)

In [3]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = x ** 2 + b
  dy_dx = tape.gradient(y, x)

del tape

In [4]:
print(dy_dx)

tf.Tensor(200.0, shape=(), dtype=float32)


In [5]:
x = tf.constant(20.0)
b = tf.constant(10.0)

with tf.GradientTape(persistent=True) as tape:
  tape.watch(x)
  tape.watch(b)
  y = x ** 2 + b ** 2
  dy_dx = tape.gradient(y, x)
  dy_db = tape.gradient(y, b)

del tape

In [6]:
print(dy_dx)
print(dy_db)

tf.Tensor(40.0, shape=(), dtype=float32)
tf.Tensor(20.0, shape=(), dtype=float32)


In [7]:
x = tf.constant(20.0)
b = tf.constant(10.0)

with tf.GradientTape(persistent=True) as tape:
    y = x ** 2 + b ** 2
dy_dx, dy_db = tape.gradient(y, [x, b])

In [8]:
print(dy_dx)
print(dy_db)

None
None


In [9]:
x = tf.Variable(20.0)
b = tf.Variable(10.0)

with tf.GradientTape(persistent=True) as tape:
    y = x ** 2 + b ** 2
dy_dx, dy_db = tape.gradient(y, [x, b])

In [10]:
print(dy_dx)
print(dy_db)

tf.Tensor(40.0, shape=(), dtype=float32)
tf.Tensor(20.0, shape=(), dtype=float32)


In [11]:
x = tf.Variable(20.0)
b = tf.Variable(10.0)

with tf.GradientTape(persistent=True) as tape2:
  with tf.GradientTape(persistent=True) as tape1:
    y = x ** 2 + b ** 2
dy_dx = tape1.gradient(y, x)
dy_dx_1 = tape2.gradient(dy_dx, x)

In [12]:
print(dy_dx)
print(dy_dx_1)

tf.Tensor(40.0, shape=(), dtype=float32)
None


In [13]:
x = tf.Variable(20.0)
b = tf.Variable(10.0)

with tf.GradientTape(persistent=True) as tape2:
  with tf.GradientTape(persistent=True) as tape1:
    y = x ** 2 + b ** 2
  dy_dx = tape1.gradient(y, x)
dy_dx_1 = tape2.gradient(dy_dx, x)

In [14]:
print(dy_dx)
print(dy_dx_1)

tf.Tensor(40.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [17]:
x = tf.Variable([-3,-2,-1,0,1,2,3])



<tf.Variable 'Variable:0' shape=(7,) dtype=int32, numpy=array([-3, -2, -1,  0,  1,  2,  3], dtype=int32)>

In [19]:
tf.math.square(x)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([9, 4, 1, 0, 1, 4, 9], dtype=int32)>

In [34]:
x = tf.Variable([-3,-2,-1,0,1,2,3],dtype=tf.float32)

with tf.GradientTape(persistent=True) as tape2:
  with tf.GradientTape(persistent=True) as tape1:
    y = tf.math.square(x)
  dy_dx = tape1.gradient(y, x)
dy_dx_1 = tape2.gradient(dy_dx, x)

In [35]:
print(dy_dx)
print(dy_dx_1)

tf.Tensor([-6. -4. -2.  0.  2.  4.  6.], shape=(7,), dtype=float32)
tf.Tensor([2. 2. 2. 2. 2. 2. 2.], shape=(7,), dtype=float32)


In [84]:
def gradientdescent(learning_rate, w0):
  with tf.GradientTape() as tape:
    y = tf.math.square(w0)

  dy_dw0 = tape.gradient(y, w0)
  w0 = w0 - learning_rate * dy_dw0
  return w0

In [85]:
w0 = tf.Variable(1.0,dtype=tf.float32)

In [72]:
w0

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [71]:
tf.Variable(gradientdescent(0.01,w0).numpy(),dtype=tf.float32)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.72>

In [90]:
for i in range(10000):
  w0 = tf.Variable(gradientdescent(0.01,w0).numpy(),dtype=tf.float32)

In [91]:
w0.numpy()

5.803526e-37