<a href="https://colab.research.google.com/github/ArunKoundinya/DeepLearning/blob/main/posts/tensor_math_operations/index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.15.0'

In [4]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [19]:
var = tf.constant([[30,40,50],[45,65,70]])

var1 = np.array([[30,40,50],[45,65,70]])

print(var)
print(" ")
print(var1)

tf.Tensor(
[[30 40 50]
 [45 65 70]], shape=(2, 3), dtype=int32)
 
[[30 40 50]
 [45 65 70]]


In [21]:
print(var * -1 )
print(" ")
print(var1 * -1 )

tf.Tensor(
[[-30 -40 -50]
 [-45 -65 -70]], shape=(2, 3), dtype=int32)
 
[[-30 -40 -50]
 [-45 -65 -70]]


In [23]:
print(tf.math.abs(var * -1))
print("")
print(np.abs(var1 * -1))

tf.Tensor(
[[30 40 50]
 [45 65 70]], shape=(2, 3), dtype=int32)

[[30 40 50]
 [45 65 70]]


In [25]:
print(tf.math.argmax(var))
print("")
print(np.argmax(var1))

tf.Tensor([1 1 1], shape=(3,), dtype=int64)

5


In [26]:
print(tf.math.argmax(var,axis=0))
print("")
print(np.argmax(var1,axis=0))

tf.Tensor([1 1 1], shape=(3,), dtype=int64)

[1 1 1]


In [27]:
print(tf.math.argmax(var,axis=1))
print("")
print(np.argmax(var1,axis=1))

tf.Tensor([2 2], shape=(2,), dtype=int64)

[2 2]


In [29]:
print(tf.math.reduce_max(var))
print("")
print(np.max(var1))

tf.Tensor(70, shape=(), dtype=int32)

70


In [30]:
print(tf.math.reduce_max(var,axis = 0))
print("")
print(np.max(var1,axis = 0))

tf.Tensor([45 65 70], shape=(3,), dtype=int32)

[45 65 70]


In [31]:
print(tf.math.reduce_max(var,axis = 1))
print("")
print(np.max(var1,axis = 1))

tf.Tensor([50 70], shape=(2,), dtype=int32)

[50 70]


In [38]:
print(tf.math.reduce_sum(var))
print("")
print(np.sum(var1))

tf.Tensor(300, shape=(), dtype=int32)

300


In [37]:
print(tf.math.reduce_sum(var,axis=0))
print("")
print(np.sum(var1,axis=0))

tf.Tensor([ 75 105 120], shape=(3,), dtype=int32)

[ 75 105 120]


In [48]:
print(tf.math.pow(var,2))
print("")
print(np.power(var1,2))
print("")
print(var ** 2)
print("")
print(var1 ** 2)

tf.Tensor(
[[ 900 1600 2500]
 [2025 4225 4900]], shape=(2, 3), dtype=int32)

[[ 900 1600 2500]
 [2025 4225 4900]]

tf.Tensor(
[[ 900 1600 2500]
 [2025 4225 4900]], shape=(2, 3), dtype=int32)

[[ 900 1600 2500]
 [2025 4225 4900]]


In [53]:
var = tf.cast(var, tf.float32)

print(tf.math.log(var))
print("")
print(np.log(var1))

tf.Tensor(
[[3.4011974 3.6888795 3.912023 ]
 [3.8066626 4.1743875 4.248495 ]], shape=(2, 3), dtype=float32)

[[3.40119738 3.68887945 3.91202301]
 [3.80666249 4.17438727 4.24849524]]


In [54]:
var = tf.cast(var, tf.int32)

print(tf.math.log(var))
print("")
print(np.log(var1))

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log] name: 

In [56]:
print(var)
print("")
print(var1)

tf.Tensor(
[[30 40 50]
 [45 65 70]], shape=(2, 3), dtype=int32)

[[30 40 50]
 [45 65 70]]


In [58]:
var = tf.cast(var, tf.float32)

print(tf.math.exp(var))
print("")
print(np.exp(var1))

tf.Tensor(
[[1.0686474e+13 2.3538525e+17 5.1847055e+21]
 [3.4934271e+19 1.6948892e+28 2.5154387e+30]], shape=(2, 3), dtype=float32)

[[1.06864746e+13 2.35385267e+17 5.18470553e+21]
 [3.49342711e+19 1.69488924e+28 2.51543867e+30]]


In [59]:
print(tf.math.sqrt(var))
print("")
print(np.sqrt(var1))

tf.Tensor(
[[5.4772253 6.3245554 7.071068 ]
 [6.708204  8.062258  8.3666   ]], shape=(2, 3), dtype=float32)

[[5.47722558 6.32455532 7.07106781]
 [6.70820393 8.06225775 8.36660027]]
