<a href="https://colab.research.google.com/github/ArunKoundinya/DeepLearning/blob/main/posts/tensor_multi_layer_linear/index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
import tensorflow.keras.layers as tfl

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

%load_ext rpy2.ipython

In [2]:
x1 = np.random.normal(size=10000)
x2 = np.random.normal(size=10000) * 2
x3 = np.power(x1,2)

y = x1 + x2 + x3

y1 = (x1 * np.exp(x2) + np.exp(-x3) * x2 ) * x1 + y

finaldf = pd.DataFrame({
    "X1" : x1,
    "X2" : x2,
    "X3" : x3,
    "Y"  : y
})

finaldf1 = pd.DataFrame({
    "X1" : x1,
    "X2" : x2,
    "X3" : x3,
    "Y"  : y1
})

print(finaldf.head())

print(finaldf1.head())

         X1        X2        X3         Y
0  1.524132 -0.934670  2.322977  2.912439
1 -0.813685  3.410324  0.662084  3.258723
2  0.183997 -3.398534  0.033855 -3.180682
3  0.161710 -4.845459  0.026150 -4.657599
4 -0.567619  3.020272  0.322191  2.774844
         X1        X2        X3          Y
0  1.524132 -0.934670  2.322977   3.685127
1 -0.813685  3.410324  0.662084  21.872114
2  0.183997 -3.398534  0.033855  -3.784055
3  0.161710 -4.845459  0.026150  -5.420728
4 -0.567619  3.020272  0.322191   8.136591


In [3]:
X = finaldf[["X1","X2","X3"]]
Y = finaldf[["Y"]]

In [4]:
lmmodel = LinearRegression()

lmmodel.fit(X,Y)

LinearRegression()

In [5]:
lmmodel.coef_

array([[1., 1., 1.]])

In [6]:
y_pred = lmmodel.predict(X)

mean_squared_error(Y, y_pred)

2.3287394852055727e-30

In [7]:
X1 = finaldf1[["X1","X2","X3"]]
Y1 = finaldf1[["Y"]]

In [8]:
lmmodel1 = LinearRegression()

lmmodel1.fit(X1,Y1)

LinearRegression()

In [9]:
lmmodel1.coef_

array([[2.69112711, 8.39388391, 9.43535975]])

In [10]:
y_pred = lmmodel.predict(X1)

mean_squared_error(Y1, y_pred)

4385.825525517447

In [11]:
modetf = tf.keras.Sequential([
    tfl.Dense(1,
              input_shape = (3,),
              activation = "linear"
              )
])

In [12]:
modetf.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4 (16.00 Byte)
Trainable params: 4 (16.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
modetf.compile(optimizer = "sgd",
               loss = "mean_squared_error",
               metrics = ["mse"])

modetf.fit(X,Y,epochs=100, verbose=0)

In [14]:
modetf.layers[0].get_weights()

[array([[1.0000002 ],
        [0.99999994],
        [1.        ]], dtype=float32),
 array([1.8922645e-08], dtype=float32)]

In [15]:
mean_squared_error(Y, modetf.predict(X).flatten())

313/313 [==============================] - 1s 1ms/step


8.450062478432384e-14

In [16]:
modetf.fit(X1,Y1,epochs=100,verbose=0)

In [17]:
modetf.layers[0].get_weights()

[array([[ 7.9459767],
        [10.005791 ],
        [19.434795 ]], dtype=float32),
 array([-2.91453], dtype=float32)]

In [18]:
mean_squared_error(Y1, modetf.predict(X1).flatten())

313/313 [==============================] - 0s 1ms/step


4279.216985484737

In [19]:
modetf1 = tf.keras.Sequential([
    tfl.Dense(100,
              input_shape = (3,),
              activation = "linear"
              ),
    tfl.Dense(1,
              activation = "linear"
              )
])

In [20]:
modetf1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 100)               400       
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 501 (1.96 KB)
Trainable params: 501 (1.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
modetf1.compile(optimizer = "sgd",
               loss = "mean_squared_error",
               metrics = ["mse"])

modetf1.fit(X,Y,epochs=100, verbose=0)

In [22]:
mean_squared_error(Y, modetf1.predict(X).flatten())

313/313 [==============================] - 1s 2ms/step


3.834542424936751e-14

In [23]:
modetf1.fit(X1,Y1,epochs=100, verbose=0)
#modetf2_pred =
#mean_squared_error(Y, modetf2_pred.flatten())
mean_squared_error(Y1, np.nan_to_num(modetf1.predict(X1)).flatten())

313/313 [==============================] - 0s 1ms/step


4506.472209255081

In [24]:
modetf2 = tf.keras.Sequential([
    tfl.Dense(4,
              input_shape = (3,),
              activation = "linear"
              ),
    tfl.Dense(3,
              input_shape = (3,),
              activation = "sigmoid"
              ),
    tfl.Dense(1,
              activation = "linear"
              )
])

In [25]:
modetf2.compile(optimizer = "sgd",
               loss = "mean_squared_error",
               metrics = ["mse"])

modetf2.fit(X,Y,epochs=100, verbose=0)

In [26]:
modetf2_pred = np.nan_to_num(modetf2.predict(X))
mean_squared_error(Y, modetf2_pred.flatten())


313/313 [==============================] - 0s 1ms/step


0.013774647608438807

In [27]:
modetf2.fit(X1,Y1,epochs=100, verbose=0)
mean_squared_error(Y1, np.nan_to_num(modetf2.predict(X1)).flatten())

313/313 [==============================] - 0s 1ms/step


4385.579539532295

In [28]:
modetf3 = tf.keras.Sequential([
    tfl.Dense(3,
              input_shape = (3,),
              activation = "relu"
              ),
    tfl.Dense(6,
              activation = "sigmoid"
              ),
    tfl.Dense(12,
              activation = "sigmoid"
              ),
    tfl.Dense(6,
              activation = "sigmoid"
              ),
    tfl.Dense(1,
              activation = "linear"
              )
])

modetf3.compile(optimizer = "sgd",
               loss = "mean_squared_error",
               metrics = ["mse"])

modetf3.fit(X1,Y1,epochs=1000, verbose=0)

mean_squared_error(Y1, modetf3.predict(X1).flatten())

313/313 [==============================] - 1s 2ms/step


4433.14019525845